#!/bin/bash

readonly START_SCRIPT_FILE="#SBIN_DIR#/start-server"
readonly STOP_SCRIPT_FILE="#SBIN_DIR#/stop-server"
readonly PID_FILE="/var/run/knb-uwsgi.pid"

function start() {
  "${START_SCRIPT_FILE}"
}

function stop() {
  "${STOP_SCRIPT_FILE}"
}

function status() {
  local _pid

  if [ -r "${PID_FILE}" ]; then
    _pid=$(cat "${PID_FILE}")
    echo "knb (pid  ${_pid}) is running..."
  else
    echo "knb is not running..."
  fi
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  restart)
    stop
    start
    ;;
  status)
    status
    ;;
  *)
	  echo $"Usage: $0 {start|stop|restart|status}"
	  exit 2
esac
