#!/bin/bash

readonly PID_FILE="/var/run/knb-uwsgi.pid"

sudo cat "${PID_FILE}" | sudo xargs kill
while :
do
  rc=$(cat "${PID_FILE}" > /dev/null 2>&1 ; echo $?)
  if [ $rc -eq 1 ]; then
    break
  fi
done
